// Generates skills/unscripted-ui/references/ from the repo's single sources of
// truth: src/demos/ (fragments), src/content/components/ (docs prose),
// src/data/features.ts (support/fallback registry) and src/styles/global.css
// (the token paste). SKILL.md is hand-written and NOT touched by this script.
//
// Run after changing any demo, docs page or feature entry:  npm run build:skill

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = path.join(root, 'src/content/components');
const demosDir = path.join(root, 'src/demos');
const outDir = path.join(root, 'skills/unscripted-ui/references');

const { FEATURES } = await import(path.join(root, 'src/data/features.ts'));

const GENERATED_NOTE = `<!-- GENERATED by scripts/build-skill.mjs — do not edit by hand.
     Sources: src/demos/, src/content/components/, src/data/features.ts -->`;

function parseFrontmatter(source) {
  const match = source.match(/^---\n([\s\S]*?)\n---\n/);
  if (!match) throw new Error('missing frontmatter');
  const fm = {};
  for (const line of match[1].split('\n')) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (kv) fm[kv[1]] = kv[2];
  }
  const features = (fm.features ?? '[]')
    .replace(/[[\]]/g, '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  return { title: fm.title, description: fm.description, features, body: source.slice(match[0].length) };
}

async function renderBody(body) {
  // Drop the MDX import; everything else in these pages is plain markdown.
  body = body.replace(/^import ComponentPreview.*\n/m, '');

  // Inline each <ComponentPreview demo="a/b" [css="a/c"] /> as code blocks.
  const previews = [...body.matchAll(/<ComponentPreview\s+([^>]*?)\/>/g)];
  for (const [tag, attrs] of previews.map((m) => [m[0], m[1]])) {
    const demo = attrs.match(/demo="([^"]+)"/)?.[1];
    if (!demo) throw new Error(`ComponentPreview without demo attr: ${tag}`);
    const css = attrs.match(/css="([^"]+)"/)?.[1];
    const html = await readFile(path.join(demosDir, `${demo}.html`), 'utf8');
    let replacement = `\`\`\`html\n${html.trimEnd()}\n\`\`\``;
    if (css) {
      const cssText = await readFile(path.join(demosDir, `${css}.css`), 'utf8');
      replacement += `\n\nRequired CSS (\`${css}.css\`):\n\n\`\`\`css\n${cssText.trimEnd()}\n\`\`\``;
    }
    body = body.replace(tag, replacement);
  }
  return body.trim();
}

function renderFeatures(keys) {
  if (keys.length === 0) {
    return 'None. This component uses only Baseline CSS/HTML — it works the same in every current browser.';
  }
  return keys
    .map((key) => {
      const f = FEATURES[key];
      if (!f) throw new Error(`unknown feature key: ${key}`);
      return `- **${f.label}** ([MDN](${f.mdn}))\n  Without it: ${f.fallback}`;
    })
    .join('\n');
}

async function buildTokensPaste() {
  // Same slice the Installation page ships — one source of truth.
  const globalCss = await readFile(path.join(root, 'src/styles/global.css'), 'utf8');
  const START = '@custom-variant dark';
  const END = '/* ============== end of the token paste ==============';
  const startIndex = globalCss.indexOf(START);
  const endIndex = globalCss.indexOf(END);
  if (startIndex === -1 || endIndex === -1)
    throw new Error('build-skill: token paste markers not found in global.css');
  return `@import "tailwindcss";\n\n${globalCss.slice(startIndex, endIndex).trimEnd()}\n`;
}

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const slugs = (await readdir(contentDir)).filter((f) => f.endsWith('.mdx')).map((f) => f.replace(/\.mdx$/, ''));
const index = [];

for (const slug of slugs.sort()) {
  const source = await readFile(path.join(contentDir, `${slug}.mdx`), 'utf8');
  const { title, description, features, body } = parseFrontmatter(source);
  index.push({ slug, title, description, features });

  const doc = `${GENERATED_NOTE}

# ${title}

${description}

${await renderBody(body)}

## Leading-edge features used (and what happens without them)

${renderFeatures(features)}
`;
  await writeFile(path.join(outDir, `${slug}.md`), doc);
}

const indexDoc = `${GENERATED_NOTE}

# Component index

One reference file per component. Read \`references/<slug>.md\` for the copyable
fragment(s), the explanation of the technique, and per-feature fallback behavior.

| Component | File | Description | Leading-edge features |
| --- | --- | --- | --- |
${index
  .map(
    (c) =>
      `| ${c.title} | \`${c.slug}.md\` | ${c.description.replaceAll('|', '\\|')} | ${c.features.join(', ') || '—'} |`,
  )
  .join('\n')}
`;
await writeFile(path.join(outDir, 'index.md'), indexDoc);

const installation = `${GENERATED_NOTE}

# Installation

There is nothing to install — no package, no provider, no registry command. The
components are markup. Setup is:

## 1. Have Tailwind CSS v4

Components are styled with Tailwind utility classes, including the newer variants
(\`starting:\`, \`transition-discrete\`, \`details-content:\`). Any Tailwind v4.1+
setup works — Vite plugin, PostCSS, or the CLI.

## 2. Paste the tokens (if needed)

This is the shadcn variable contract mapped to Tailwind v4's \`@theme\`. **If the
project already uses shadcn/ui, it already has these variables** — skip the
\`:root\`/\`.dark\` blocks and keep the existing theme; the components will match it
automatically. The paste also carries the global \`prefers-reduced-motion\` rule the
components rely on. The \`dark\` variant is class-driven: add \`.dark\` to \`<html>\`
however the project likes.

\`\`\`css
${(await buildTokensPaste()).trimEnd()}
\`\`\`

## 3. Copy components

Paste the fragment from the component's reference file into the page. Exactly one
component (Carousel) ships an extra CSS block; its reference explains why.

## Optional: dialog invoker shim

Dialog, Alert Dialog and Drawer open via invoker commands (\`commandfor\`/\`command\`).
In browsers that don't ship them yet, the buttons do nothing. If the audience includes
those browsers, add this small shim (or open the dialog from the project's framework) —
it is inert wherever invoker commands are native:

\`\`\`js
if (!('command' in HTMLButtonElement.prototype)) {
  document.addEventListener('click', (event) => {
    const invoker = event.target.closest?.('button[commandfor]');
    if (!invoker) return;
    const dialog = document.getElementById(invoker.getAttribute('commandfor'));
    if (!(dialog instanceof HTMLDialogElement)) return;
    const command = invoker.getAttribute('command');
    if (command === 'show-modal' && !dialog.open) dialog.showModal();
    if (command === 'close') dialog.close();
  });
}
\`\`\`
`;
await writeFile(path.join(outDir, 'installation.md'), installation);

console.log(`build-skill: wrote ${slugs.length} component references + index.md + installation.md to ${path.relative(root, outDir)}`);
